name: Awesome-CV-CI

on:
  schedule:
  - cron: "0 2 * * *"
jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olivierodo/awesome-cv-action@0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'resume.tex'
        LATEST_TAG: 'true' # set to false if you don't want an auto tag of latest (default: true)
